name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Install Compatible ChromeDriver
        run: |
          set -e  # Exit on error

          # Attempt to get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' || echo "")
          if [ -z "$CHROME_VERSION" ]; then
            echo "Failed to retrieve Chrome version. Attempting to fetch the latest stable version."
            CHROME_VERSION=$(curl -sS https://omahaproxy.appspot.com/all.json | jq -r '.[0].versions[] | select(.channel=="stable") | .version' || echo "")
            if [ -z "$CHROME_VERSION" ]; then
              echo "Failed to retrieve Chrome version. Ensure Google Chrome is installed properly."
              exit 1
            fi
          fi

          # Fetch ChromeDriver version
          DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}" || echo "")
          if [ -z "$DRIVER_VERSION" ]; then
            echo "Failed to fetch ChromeDriver version for Chrome version $CHROME_VERSION."
            echo "Using fallback version: 114.0.5735.90"
            DRIVER_VERSION="114.0.5735.90" # Replace with updated fallback version if needed
          fi

          # Download and install ChromeDriver
          wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          if [ $? -ne 0 ]; then
            echo "Failed to download ChromeDriver. Verify the DRIVER_VERSION and network connectivity."
            exit 1
          fi

          unzip -o chromedriver_linux64.zip -d /usr/local/bin/
          rm chromedriver_linux64.zip
      - name: Check Chrome Version
        run: google-chrome --version
      - name: Check ChromeDriver Version
        run: chromedriver --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run tests
        run: make test
      - name: Run coverage
        run: make coverage
