name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable=114.0.5735.198-1
      - name: Setup ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"
          if [ -z "$CHROME_VERSION" ]; then
            echo "Failed to determine Chrome version. Please check Chrome installation."
            exit 1
          fi
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%%.*}")
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Failed to fetch ChromeDriver version for Chrome version $CHROME_VERSION"
            exit 1
          fi
          wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P /tmp/ || exit 1
          unzip /tmp/chromedriver_linux64.zip -d /tmp/
          sudo mv /tmp/chromedriver /usr/local/bin/
          rm /tmp/chromedriver_linux64.zip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run tests
        run: make test
      - name: Run coverage
        run: make coverage
